### ISSUE TITLE
Are fonts of other languages available?

### ISSUE THREAD

**Issue by Mirror995** [yell0wsuit/ZeldaGlyphs#1]
Thank you for offering the English file. It helped me a lot!
I'm also interested in the Chinese font of the game. Could you help me extract it?
Or, can you explain the procudure to extract?

**Comment by yell0wsuit** [comment]
I honestly don't know much about the Chinese/Japanese font files, but you can try extracting them from Switch version of the game (use emulator like Ryujinx or yuzu, install version 1.6 then extract). It is located in ``Content/Font``. (The font files are only in BOTW, not TOTK).

The font's extension usually starts with "sbf***", use the tools from https://zeldamods.org/wiki/Yaz0 to extract them to ttf/otf.

**Comment by Mirror995** [comment]
Following your steps, I have successfully extracted the files! Thanks a lot!Sent from my iPhoneOn Aug 23, 2023, at 5:41 PM, yell0wsuit ***@***.***> wrote:﻿
I honestly don't know much about the Chinese/Japanese font files, but you can try extracting them from Switch version of the game (use emulator like Ryujinx or yuzu, install version 1.6 then extract). It is located in Content/Font. (The font files are only in BOTW, not TOTK).
The font's extension usually starts with "sbf***", use the tools from https://zeldamods.org/wiki/Yaz0 to extract them to ttf/otf.
